version: '3'
services:
  consumer:
    build: ./consumer
    ports:
      - "8090:8090"
    depends_on:
      - rabbitmq
    network_mode: "host"
  producer:
    build: ./producer
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.8.4-management
    ports:
        - "5672:5672"
        - "15672:15672"
        - "25676:25676"